---

- name: Install nsd
  apt:
    name: nsd
    state: present

- name: Enable nsd
  service:
    name: "{{ nsd_service }}"
    enabled: true

- name: Install ldnsutils
  apt:
    name: ldnsutils
    state: present
